export const FETCH_LIST = '@@employee/FETCH_LIST'
export const RECEIVED_LIST = '@@employee/RECEIVED_LIST'
export const SAVE_NEW_RECORD = '@@employee/SAVE_NEW_RECORD'
export const DELETE_RECORD = '@@employee/DELETE_RECORD'
export const UPDATE_RECORD = '@@employee/UPDATE_RECORD'
export const RECORD_TO_VIEW = '@@employee/RECORD_TO_VIEW'
export const RECORD_INFO = '@@employee/RECORD_INFO'