export const FETCH_LIST = '@@employeeStatus/FETCH_LIST'
export const RECEIVED_LIST = '@@employeeStatus/RECEIVED_LIST'
export const SAVE_NEW_RECORD = '@@employeeStatus/SAVE_NEW_RECORD'
export const RECORD_INFO = '@@employeeStatus/RECORD_INFO'
export const DELETE_RECORD = '@@employeeStatus/DELETE_RECORD'
export const UPDATE_RECORD = '@@employeeStatus/UPDATE_RECORD'
export const RECORD_TO_VIEW = '@@employeeStatus/RECORD_TO_VIEW'